# __Analiza i Bazy Danych__
## __Laboratorium 2__
## Daniel Węgrzynowski
### gr. 3a, piątek 12:30

Celem zajęć jest zapoznanie się z protokołem TIER a także poznanie pojęcia "Tidy Data", zastosowaniu, zasad obowiązujących oraz czynności które powinniśmy wykonać przy porządkowaniu danych.

In [1]:
from IPython.core.display import display
import numpy as np
import pandas as pd


# Wczytanie pliku z danymi billboard.csv z folderu z nieobrobionymi danymi ('Original Data')
data = pd.read_csv('../Original Data/billboard.csv')

# Wyświetlenie oryginalnych danych
display(data)

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# Utworzenie tabeli z danymi piosenek (rok produkcji, artysta, nazwa piosenki, gatunek muzyczny oraz czas trwania)
data1 = data[['artist.inverted','track','genre','time']]
data1.columns=["Artist",'Track','Genre','Time']

# Dodanie id w celu integracji ze sobą 2 tabel (z danymi piosenek oraz danymi rankingowymi)
idxs = [index for index, row in data1.iterrows()]
data1.insert(0,'song id',idxs)

# Wyświetlenie utworzonej tabeli
display(data1)

# Zapisanie tabeli do pliku csv do folderu Analysis Data, gdzie znajdują się przetworzone dane
data1.to_csv('../Analysis Data/SongsData.csv')

,song id,Artist,Track,Genre,Time
0,0,Destiny's Child,Independent Women Part I,Rock,3:38
1,1,Santana,"Maria, Maria",Rock,4:18
2,2,Savage Garden,I Knew I Loved You,Rock,4:07
3,3,Madonna,Music,Rock,3:45
4,4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,3:38
...,...,...,...,...,...
312,312,Ghostface Killah,Cherchez LaGhost,R&B,3:04
313,313,"Smith, Will",Freakin' It,Rap,3:58
314,314,Zombie Nation,Kernkraft 400,Rock,3:30
315,315,"Eastsidaz, The",Got Beef,Rap,3:58
316,316,Fragma,Toca's Miracle,R&B,3:22

In [3]:
# Utworzenie tabeli z danymi rankigowymi zmiennymi w czasie odnoszącymi się do piosenek o id zgodnymi z poprzednią tabelą
data2 = data.iloc[:,7:]

# Utworzenie pustego DataFrame
ranking_data = pd.DataFrame(columns=['song id','date','rank'])

# Dodawanie do DataFrame ranking_data rekordów z id piosenki, datą oraz pozycją w rankingu
for index, row in data2.iterrows():
    date = pd.to_datetime(data.iloc[index]['date.entered'])
    for column in row:
        if str(column) != 'nan':
            week_data = pd.DataFrame([[index, date, int(column)]], columns=['song id','date','rank'])
            ranking_data = pd.concat([ranking_data, week_data], ignore_index=True)
            date = date + pd.DateOffset(7)

            


# Wyświetlenie utworzonej tabeli
display(ranking_data)

# Zapisanie tabeli do pliku csv do folderu Analysis Data, gdzie znajdują się przetworzone dane
ranking_data.to_csv('../Analysis Data/RankingData.csv')

     song id       date rank
0          0 2000-09-23   78
1          0 2000-09-30   63
2          0 2000-10-07   49
3          0 2000-10-14   33
4          0 2000-10-21   23
...      ...        ...  ...
5302     314 2000-09-02   99
5303     314 2000-09-09   99
5304     315 2000-07-01   99
5305     315 2000-07-08   99
5306     316 2000-10-28   99

[5307 rows x 3 columns]